# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jiemian.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("图标.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(700, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_load_model = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_model.setGeometry(QtCore.QRect(200, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_load_model.setFont(font)
        self.btn_load_model.setMouseTracking(False)
        self.btn_load_model.setTabletTracking(False)
        self.btn_load_model.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_load_model.setAutoFillBackground(False)
        self.btn_load_model.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.btn_load_model.setCheckable(False)
        self.btn_load_model.setChecked(False)
        self.btn_load_model.setObjectName("btn_load_model")
        self.lab_time = QtWidgets.QLabel(self.centralwidget)
        self.lab_time.setGeometry(QtCore.QRect(40, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lab_time.setFont(font)
        self.lab_time.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lab_time.setMouseTracking(False)
        self.lab_time.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.409091 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"")
        self.lab_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_time.setObjectName("lab_time")
        self.btn_output_folder = QtWidgets.QPushButton(self.centralwidget)
        self.btn_output_folder.setEnabled(True)
        self.btn_output_folder.setGeometry(QtCore.QRect(600, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_output_folder.setFont(font)
        self.btn_output_folder.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_output_folder.setObjectName("btn_output_folder")
        self.btn_open_video = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_video.setEnabled(False)
        self.btn_open_video.setGeometry(QtCore.QRect(300, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btn_open_video.setFont(font)
        self.btn_open_video.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.btn_open_video.setCheckable(True)
        self.btn_open_video.setObjectName("btn_open_video")
        self.lab_video = QtWidgets.QLabel(self.centralwidget)
        self.lab_video.setGeometry(QtCore.QRect(40, 60, 340, 350))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.lab_video.setFont(font)
        self.lab_video.setStyleSheet("*{border: 2px solid black;background-color: rgb(170, 255, 0);}\n"
"\n"
"\n"
"")
        self.lab_video.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_video.setObjectName("lab_video")
        self.radio_real_detect = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_real_detect.setEnabled(True)
        self.radio_real_detect.setGeometry(QtCore.QRect(50, 460, 181, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.radio_real_detect.setFont(font)
        self.radio_real_detect.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.radio_real_detect.setMouseTracking(False)
        self.radio_real_detect.setTabletTracking(False)
        self.radio_real_detect.setCheckable(True)
        self.radio_real_detect.setChecked(False)
        self.radio_real_detect.setAutoRepeat(False)
        self.radio_real_detect.setAutoExclusive(True)
        self.radio_real_detect.setObjectName("radio_real_detect")
        self.lab_result = QtWidgets.QLabel(self.centralwidget)
        self.lab_result.setGeometry(QtCore.QRect(420, 60, 340, 350))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.lab_result.setFont(font)
        self.lab_result.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lab_result.setToolTipDuration(-1)
        self.lab_result.setStyleSheet("*{border: 2px solid red;background-color: rgb(85, 255, 255);}\n"
"")
        self.lab_result.setScaledContents(False)
        self.lab_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_result.setObjectName("lab_result")
        self.radio_load_image_detect = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_load_image_detect.setEnabled(True)
        self.radio_load_image_detect.setGeometry(QtCore.QRect(50, 500, 181, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.radio_load_image_detect.setFont(font)
        self.radio_load_image_detect.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.radio_load_image_detect.setMouseTracking(False)
        self.radio_load_image_detect.setCheckable(True)
        self.radio_load_image_detect.setChecked(True)
        self.radio_load_image_detect.setAutoRepeat(False)
        self.radio_load_image_detect.setAutoExclusive(True)
        self.radio_load_image_detect.setObjectName("radio_load_image_detect")
        self.btn_processing_detect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_processing_detect.setEnabled(False)
        self.btn_processing_detect.setGeometry(QtCore.QRect(650, 420, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_processing_detect.setFont(font)
        self.btn_processing_detect.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 255);")
        self.btn_processing_detect.setObjectName("btn_processing_detect")
        self.btn_start_detect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_detect.setEnabled(False)
        self.btn_start_detect.setGeometry(QtCore.QRect(500, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_start_detect.setFont(font)
        self.btn_start_detect.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_start_detect.setCheckable(False)
        self.btn_start_detect.setObjectName("btn_start_detect")
        self.lab_information = QtWidgets.QLabel(self.centralwidget)
        self.lab_information.setGeometry(QtCore.QRect(240, 460, 551, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lab_information.setFont(font)
        self.lab_information.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lab_information.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_information.setObjectName("lab_information")
        self.btn_load_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_image.setEnabled(True)
        self.btn_load_image.setGeometry(QtCore.QRect(400, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_load_image.setFont(font)
        self.btn_load_image.setMouseTracking(False)
        self.btn_load_image.setTabletTracking(False)
        self.btn_load_image.setAcceptDrops(False)
        self.btn_load_image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_load_image.setAutoFillBackground(False)
        self.btn_load_image.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.btn_load_image.setCheckable(False)
        self.btn_load_image.setChecked(False)
        self.btn_load_image.setAutoRepeat(False)
        self.btn_load_image.setAutoExclusive(False)
        self.btn_load_image.setAutoDefault(False)
        self.btn_load_image.setDefault(False)
        self.btn_load_image.setFlat(False)
        self.btn_load_image.setObjectName("btn_load_image")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 420, 191, 131))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame{border: 2px solid rgb(25, 36, 255);background-color: rgb(170, 170, 255)}\n"
"\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(5, 10, 181, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("QLabel{border: 0px ;}")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.lab_time_2 = QtWidgets.QLabel(self.centralwidget)
        self.lab_time_2.setGeometry(QtCore.QRect(320, 420, 321, 71))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lab_time_2.setFont(font)
        self.lab_time_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lab_time_2.setText("")
        self.lab_time_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_time_2.setObjectName("lab_time_2")
        self.frame.raise_()
        self.btn_exit.raise_()
        self.btn_load_model.raise_()
        self.lab_time.raise_()
        self.btn_output_folder.raise_()
        self.btn_open_video.raise_()
        self.radio_real_detect.raise_()
        self.lab_result.raise_()
        self.radio_load_image_detect.raise_()
        self.btn_processing_detect.raise_()
        self.btn_start_detect.raise_()
        self.lab_information.raise_()
        self.btn_load_image.raise_()
        self.lab_video.raise_()
        self.lab_time_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "织物缺陷检测的智能终端"))
        self.btn_exit.setText(_translate("MainWindow", "退出"))
        self.btn_load_model.setText(_translate("MainWindow", "导入模型"))
        self.lab_time.setText(_translate("MainWindow", "时间显示区"))
        self.btn_output_folder.setText(_translate("MainWindow", "输出路径"))
        self.btn_open_video.setText(_translate("MainWindow", "打开摄像头"))
        self.lab_video.setText(_translate("MainWindow", "Image&Video"))
        self.radio_real_detect.setText(_translate("MainWindow", "在线检测"))
        self.lab_result.setText(_translate("MainWindow", "检测结果"))
        self.radio_load_image_detect.setText(_translate("MainWindow", "导入图片检测"))
        self.btn_processing_detect.setText(_translate("MainWindow", "查看检测过程"))
        self.btn_start_detect.setText(_translate("MainWindow", "开始检测"))
        self.lab_information.setText(_translate("MainWindow", "织物缺陷检测的智能终端"))
        self.btn_load_image.setText(_translate("MainWindow", "导入图片"))
        self.label_2.setText(_translate("MainWindow", "检测模式设置"))

